-- Generated by the manager on each launch. Controls optional features and
-- holds the manager's character list (used by the relog menu).
WowManagerConfig = {
    showMinimap = false,
    characters = {
    },
}
